### ISSUE TITLE
Label for appendix section

### ISSUE THREAD

**Issue by ralfhecktor** [schocco/DHBW-stgt-template#17]
\label{some_label} for \appsection is not working propperly. \ref{some_label} gets me the number of the last \section, \subsection or \subsubsection but not of \appsection.

**Comment by schocco** [comment]
Apparently that is because \appsection uses
`\subsection*{Appendix \arabic{appendixctr}:\hspace{15pt}#1}`
Due to the `*` the section does not have a number. The number is created inside the label and hence references to labels in this section point to the last section with a number.

**Comment by ralfhecktor** [comment]
So there is no way of dynamically referencing appendices?
